import "./globals.css";
import { inter } from "./components/Fonts";


export const metadata = {
  title: "EZ-Vendo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased text-sm sm:text-based`}
      >
        {children}
      </body>
    </html>
  );
}
